version: 1.0.{build}
os:
- Visual Studio 2015 RC
- Windows Server 2012 R2
platform: Any CPU
init:
- cmd: 
install:
- cmd: >-
    dnvm upgrade -r clr

    dnu restore
build:
  publish_wap: true
  publish_azure: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal